/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as OrderSummaryRouteImport } from './routes/order-summary'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as ProductsCategoryRouteImport } from './routes/products.$category'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'

const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSummaryRoute = OrderSummaryRouteImport.update({
  id: '/order-summary',
  path: '/order-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/products/$category',
  path: '/products/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/discover': typeof DiscoverRoute
  '/guides': typeof GuidesRouteWithChildren
  '/my-list': typeof MyListRoute
  '/order-summary': typeof OrderSummaryRoute
  '/returns': typeof ReturnsRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/brands/': typeof BrandsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/discover': typeof DiscoverRoute
  '/my-list': typeof MyListRoute
  '/order-summary': typeof OrderSummaryRoute
  '/returns': typeof ReturnsRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/brands': typeof BrandsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/discover': typeof DiscoverRoute
  '/guides': typeof GuidesRouteWithChildren
  '/my-list': typeof MyListRoute
  '/order-summary': typeof OrderSummaryRoute
  '/returns': typeof ReturnsRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/brands/': typeof BrandsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/discover'
    | '/guides'
    | '/my-list'
    | '/order-summary'
    | '/returns'
    | '/brands/$slug'
    | '/guides/$slug'
    | '/product/$id'
    | '/products/$category'
    | '/brands/'
    | '/guides/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/discover'
    | '/my-list'
    | '/order-summary'
    | '/returns'
    | '/brands/$slug'
    | '/guides/$slug'
    | '/product/$id'
    | '/products/$category'
    | '/brands'
    | '/guides'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/discover'
    | '/guides'
    | '/my-list'
    | '/order-summary'
    | '/returns'
    | '/brands/$slug'
    | '/guides/$slug'
    | '/product/$id'
    | '/products/$category'
    | '/brands/'
    | '/guides/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  DiscoverRoute: typeof DiscoverRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  MyListRoute: typeof MyListRoute
  OrderSummaryRoute: typeof OrderSummaryRoute
  ReturnsRoute: typeof ReturnsRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  ProductIdRoute: typeof ProductIdRoute
  ProductsCategoryRoute: typeof ProductsCategoryRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-summary': {
      id: '/order-summary'
      path: '/order-summary'
      fullPath: '/order-summary'
      preLoaderRoute: typeof OrderSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  DiscoverRoute: DiscoverRoute,
  GuidesRoute: GuidesRouteWithChildren,
  MyListRoute: MyListRoute,
  OrderSummaryRoute: OrderSummaryRoute,
  ReturnsRoute: ReturnsRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  ProductIdRoute: ProductIdRoute,
  ProductsCategoryRoute: ProductsCategoryRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
